FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential sudo

COPY . /repo
WORKDIR /repo
RUN chmod +x createDebFromSourceUbuntu.bash
RUN ./createDebFromSourceUbuntu.bash --prefix=/install

FROM ubuntu:20.04 as package
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y libva-dev libvdpau-dev libsqlite3-dev
COPY --from=builder /install /install
ENV LD_LIBRARY_PATH=/install/lib